### ISSUE TITLE
Can't install pcap on windows 10

### ISSUE THREAD

**Issue by Chris2011** [node-pcap/node_pcap#190]
When I try to install the pcap:

``` bash
npm install pcap --save
```

I got this error message:

```
C:\Projekte\Others\ProjectName>npm install pcap --save
npm WARN package.json ProjectName@1.0.0 No description
npm WARN package.json ProjectName@1.0.0 No repository field.
npm WARN package.json ProjectName@1.0.0 No README data
npm WARN package.json ProjectName@1.0.0 No license field.
|
> socketwatcher@0.2.1 install C:\Projekte\Others\ProjectName\node_modules\pcap\node_modules\socketwatcher
> node-gyp rebuild


C:\Projekte\Others\ProjectName\node_modules\pcap\node_modules\socketwatcher>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu ermöglichen, müssen Sie den Schalter "/m" hinzufügen.
  TRACKER : Fehler TRK0005: Fehler beim Suchen von "CL.exe". Das System kann die angegebene Datei nicht finden.


C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(355,5): error MSB6006: "CL.exe" wurde mit dem Code 5 beendet. [C:\Projekte\Others\ProjectName\node_modules\p cap\node_modules\socketwatcher\build\socketwatcher.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Projekte\Others\ProjectName\node_modules\pcap\node_modules\socketwatcher
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "pcap" "--save"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! socketwatcher@0.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the socketwatcher@0.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the socketwatcher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls socketwatcher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projekte\Others\ProjectName\npm-debug.log
```

My enviroment is:
Windows 10 64Bit
Node 4.0.0
npm 2.14.2

Do you need more info?
It says that there is a problem with the socketwatcher.

Cheers

Chris

**Comment by Chris2011** [comment]
Unfortunatly I still get the exception. Node is 10.16.2 and npm is 6.11.3. Python was set to the correct path.

Will now use the cap package. It seems better maintained. Just FYI.
