### ISSUE TITLE
Can't install on Win7 x64

### ISSUE THREAD

**Issue by inf3rno** [node-pcap/node_pcap#224]
I installed node-gyp and [winpcap](https://www.winpcap.org/), but this got the following error message. Any idea on this?
```

$ npm install pcap -g

> pcap@2.0.1 install C:\Users\inf3rno\AppData\Roaming\npm\node_modules\pcap
> node-gyp rebuild


C:\Users\inf3rno\AppData\Roaming\npm\node_modules\pcap>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  pcap_binding.cc
  pcap_session.cc
  win_delay_load_hook.cc
..\pcap_binding.cc(2): fatal error C1083: Cannot open include file: 'pcap/pcap.h': No such file or directory [C:\Users\inf3rno\AppData\Roaming\npm\node_modules\pcap\build\pcap_binding.vcxproj]
..\pcap_session.cc(2): fatal error C1083: Cannot open include file: 'pcap/pcap.h': No such file or directory [C:\Users\inf3rno\AppData\Roaming\npm\node_modules\pcap\build\pcap_binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\inf3rno\AppData\Roaming\npm\node_modules\pcap
gyp ERR! node -v v8.1.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pcap@2.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcap@2.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\inf3rno\AppData\Roaming\npm-cache\_logs\2017-06-21T00_17_05_237Z-debug.log

```

**Comment by LiamKarlMitchell** [comment]
Same.
There are other issues about windows support. (lack)
https://github.com/node-pcap/node_pcap/issues/95

**Comment by inf3rno** [comment]
@LiamKarlMitchell I found another project with Windows support: https://github.com/mscdex/cap I'll try to capture ARP broadcasts with that, maybe...

**Comment by LiamKarlMitchell** [comment]
@inf3rno Awesome thank you, I shall give it a go next time I fancy tinkering with the capturing on windows.
Although, I did have trouble with other things in the  past capturing loopback traffic on windows, ended up using a VM.
I wonder if this could be merged into here for both windows & nix support?

**Comment by inf3rno** [comment]
@LiamKarlMitchell Probably. It uses winpcap.

**Comment by LiamKarlMitchell** [comment]
By the way I tried this out recently on windows.
https://nmap.org/npcap/
WinPcap for Windows 10 Npcap works on Windows 7 and later by making use of the new NDIS 6 Light-Weight Filter API.

Once installed and rebooted PC I was able to use it to capture local traffic with wireshark.
