### ISSUE TITLE
Problem with install Homebridge-Dash

### ISSUE THREAD

**Issue by jlngnr** [node-pcap/node_pcap#228]
Please i need help.
I have a problem with install the Plugin Homebridge-Dash on my Raspberry homebridge.
The log. is:

>0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'homebridge-dash' ]
2 info using npm@4.2.0
3 info using node@v7.10.1
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData homebridge-dash
8 silly fetchNamedPackageData homebridge-dash
9 silly mapToRegistry name homebridge-dash
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'homebridge-dash',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   escapedName: 'homebridge-dash',
12 silly mapToRegistry   name: 'homebridge-dash',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/homebridge-dash
14 verbose request uri https://registry.npmjs.org/homebridge-dash
15 verbose request no auth needed
16 info attempt registry request try #1 at 14:53:38
17 verbose request id c350177439ae35da
18 verbose etag W/"5957f92d-9d1"
19 verbose lastModified Sat, 01 Jul 2017 19:34:05 GMT
20 http request GET https://registry.npmjs.org/homebridge-dash
21 http 304 https://registry.npmjs.org/homebridge-dash
22 verbose headers { date: 'Fri, 21 Jul 2017 12:53:38 GMT',
22 verbose headers   via: '1.1 varnish',
22 verbose headers   'cache-control': 'max-age=300',
22 verbose headers   etag: 'W/"5957f92d-9d1"',
22 verbose headers   age: '0',
22 verbose headers   connection: 'keep-alive',
22 verbose headers   'x-served-by': 'cache-hhn1533-HHN',
22 verbose headers   'x-cache': 'HIT',
22 verbose headers   'x-cache-hits': '1',
22 verbose headers   'x-timer': 'S1500641619.773293,VS0,VE28',
22 verbose headers   vary: 'Accept-Encoding, Accept' }
23 silly get cb [ 304,
23 silly get   { date: 'Fri, 21 Jul 2017 12:53:38 GMT',
23 silly get     via: '1.1 varnish',
23 silly get     'cache-control': 'max-age=300',
23 silly get     etag: 'W/"5957f92d-9d1"',
23 silly get     age: '0',
23 silly get     connection: 'keep-alive',
23 silly get     'x-served-by': 'cache-hhn1533-HHN',
23 silly get     'x-cache': 'HIT',
23 silly get     'x-cache-hits': '1',
<
and it says during the install:
<pi@raspberrypi:~ $ sudo npm install -g homebridge-dash

> socketwatcher@0.3.0 install /usr/lib/node_modules/homebridge-dash/node_modules/socketwatcher
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/homebridge-dash/node_modules/socketwatcher/.node-gyp"
make: Entering directory '/usr/lib/node_modules/homebridge-dash/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
../socket_watcher.cpp: In static member function ‘static void SocketWatcher::New(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../socket_watcher.cpp:104:49: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated (declared at /usr/lib/node_modules/homebridge-dash/node_modules/socketwatcher/.node-gyp/7.10.1/include/node/v8.h:3662): Use maybe version [-Wdeprecated-declarations]
     info.GetReturnValue().Set(cons->NewInstance());
                                                 ^
  SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
  COPY Release/socketwatcher.node
make: Leaving directory '/usr/lib/node_modules/homebridge-dash/node_modules/socketwatcher/build'

> pcap@2.0.0 install /usr/lib/node_modules/homebridge-dash/node_modules/pcap
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.10.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/homebridge-dash/node_modules/pcap/.node-gyp"
make: Entering directory '/usr/lib/node_modules/homebridge-dash/node_modules/pcap/build'
  CXX(target) Release/obj.target/pcap_binding/pcap_binding.o
../pcap_binding.cc:2:23: fatal error: pcap/pcap.h: Datei oder Verzeichnis nicht gefunden
 #include <pcap/pcap.h>
                       ^
compilation terminated.
pcap_binding.target.mk:93: recipe for target 'Release/obj.target/pcap_binding/pcap_binding.o' failed
make: *** [Release/obj.target/pcap_binding/pcap_binding.o] Error 1
make: Leaving directory '/usr/lib/node_modules/homebridge-dash/node_modules/pcap/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.9.35-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-dash/node_modules/pcap
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
/usr/lib
└── (empty)

npm ERR! Linux 4.9.35-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "homebridge-dash"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! pcap@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pcap@2.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pcap package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pcap
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pcap
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-07-21T13_10_23_668Z-debug.log
> 
Please when you can answer in german please do it. I stay  there
Thanks

**Comment by jlngnr** [comment]
No Idea anyone?

**Comment by jlngnr** [comment]
No Idea?

**Comment by TincaTibo** [comment]
Hi

Looks like there is not libpcap installed on your distribution since it
cannot load pcap.h

Cheers,
Thibaut

**Comment by jlngnr** [comment]
No Sorry. I hav libcap installed First as i installed homebridge

**Comment by TincaTibo** [comment]
And libpcap-dev?

**Comment by zetflo** [comment]
install libpcap-dev works for me thx
