### ISSUE TITLE
make it nodejs 12 compatible ...

### ISSUE THREAD

**Issue by Apollon77** [node-pcap/node_pcap#251]
reason seems to be socketwatcher fort the beginning:

```
> socketwatcher@0.3.0 install /home/travis/build/Apollon77/ioBroker.amazon-dash/node_modules/socketwatcher
> node-gyp rebuild
make: Entering directory `/home/travis/build/Apollon77/ioBroker.amazon-dash/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
../socket_watcher.cpp: In static member function ‘static void SocketWatcher::Initialize(v8::Local<v8::Object>)’:
../socket_watcher.cpp:29:36: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   constructor.Reset(t->GetFunction());
                                    ^
In file included from /home/travis/.node-gyp/12.2.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:53,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
/home/travis/.node-gyp/12.2.0/include/node/v8.h:5947:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/travis/.node-gyp/12.2.0/include/node/v8.h:5947:46: note:   candidate expects 1 argument, 0 provided
../socket_watcher.cpp:30:75: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
   exports->Set(Nan::New("SocketWatcher").ToLocalChecked(), t->GetFunction());
                                                                           ^
In file included from /home/travis/.node-gyp/12.2.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:53,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
/home/travis/.node-gyp/12.2.0/include/node/v8.h:5947:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/travis/.node-gyp/12.2.0/include/node/v8.h:5947:46: note:   candidate expects 1 argument, 0 provided
../socket_watcher.cpp: In static member function ‘static void SocketWatcher::Callback(uv_poll_t*, int, int)’:
../socket_watcher.cpp:77:60: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(watcher->handle(), callback, argc, argv);
                                                            ^
In file included from ../socket_watcher.hpp:8:0,
                 from ../socket_watcher.cpp:5:
../../nan/nan.h:959:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../socket_watcher.cpp: In static member function ‘static void SocketWatcher::Set(const Nan::FunctionCallbackInfo<v8::Value>&)’:
../socket_watcher.cpp:116:32: error: no matching function for call to ‘v8::Value::Int32Value()’
   int fd = info[0]->Int32Value();
                                ^
In file included from /home/travis/.node-gyp/12.2.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:53,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
/home/travis/.node-gyp/12.2.0/include/node/v8.h:2569:40: note: candidate: v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
                                        ^~~~~~~~~~
/home/travis/.node-gyp/12.2.0/include/node/v8.h:2569:40: note:   candidate expects 1 argument, 0 provided
make: *** [Release/obj.target/socketwatcher/socket_watcher.o] Error 1
make: Leaving directory `/home/travis/build/Apollon77/ioBroker.amazon-dash/node_modules/socketwatcher/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v12.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
gyp ERR! System Linux 4.4.0-101-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v12.2.0/bin/node" "/home/travis/.nvm/versions/node/v12.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/Apollon77/ioBroker.amazon-dash/node_modules/socketwatcher
gyp ERR! node -v v12.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! socketwatcher@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the socketwatcher@0.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2019-05-14T15_21_17_104Z-debug.log
```

**Comment by guoper59** [comment]
same issue here

**Comment by lesmo** [comment]
I can confirm rolling back to current LTS release of Node solves the issue.

**Comment by guoper59** [comment]
It is working on 11 too.

**Comment by bnonni** [comment]
Confirming install works if you roll back from node@12 to node@10. I did the following:
```
$ brew unlink node
$ brew install node@10 (or 11 apparently, I used 10 via brew)
$ brew link node@10 
```
Then try your npm install pcap in your app directory. I got a number of warnings, but no errors, which is a huge step forward.

**Comment by Apollon77** [comment]
Sorry, but all the posts about "it works in nodejs <12" do not really help so solve the issue ;-) It stay with: It is not working with nodejs 12 :-(

The question seems more if this project is dead? :-(

**Comment by roccomuso** [comment]
PRs are welcome

**Comment by Apollon77** [comment]
I know ... as soon as I find some spare time to dig into that native part development (it is try and error for me and cost looong time) I will do.

But currently I have other prios and i‘m also not having such devices. So it would be a blind fix just to make eure it compiles. Don‘t know if this would be the best idea. :-(

**Comment by jonahharris** [comment]
#254

**Comment by fezzz** [comment]
Thanks to jonahharris for the pull-request waiting to be accepted in den socketwatcher-repo.
Unfortunately socketwatcher seems not to be maintained any more...

Could you maybe change the dependeny to jonah's fixed version in the meantime?
https://github.com/jonahharris/node-socketwatcher/tree/with-v12-fixes 

Thanks, Felix

**Comment by jonahharris** [comment]
Given its unmaintained, NPM gave me ownership of the socketwatcher repo. I need to push the new version.

**Comment by Apollon77** [comment]
closed why? Is there a new version available?

**Comment by roccomuso** [comment]
@Apollon77 yes, we merged this in a different PR and will release a new pcap version asap.

**Comment by Apollon77** [comment]
cool Thank you!

**Comment by mildsunrise** [comment]
v3 is up, let us know if you have any problems with it :)
keep in mind the api changes a bit

**Comment by Apollon77** [comment]
I already have some guys test my project with the github as dependency :-)
